// SUB PHOTOS

// export const products = [
//   {
//     id: faker.string.uuid(),
//     name: 'Comfort Cove',
//     price: Number(faker.commerce.price({ min: 1000, max: 5000 })),
//     stock: Math.floor(Math.random() * 100),
//     qty: 0,
//     image: GraySofa,
//     subPhotos: [GraySofaSub, GraySofaSub2],
//     category: ProductCategory.SOFA,
//     isFeatured: true,
//     createdAt: faker.date.recent(),
//   },
//   {
//     id: faker.string.uuid(),
//     name: 'Zenith Lounge',
//     price: Number(faker.commerce.price({ min: 1000, max: 5000 })),
//     stock: Math.floor(Math.random() * 100),
//     qty: 0,
//     image: BlackChair,
//     subPhotos: [],
//     category: ProductCategory.CHAIR,
//     isFeatured: true,
//     createdAt: faker.date.recent(),
//   },
//   {
//     id: faker.string.uuid(),
//     name: 'Bliss Haven',
//     price: Number(faker.commerce.price({ min: 1000, max: 5000 })),
//     stock: Math.floor(Math.random() * 100),
//     qty: 0,
//     image: GreenSofa,
//     subPhotos: [],
//     category: ProductCategory.SOFA,
//     isFeatured: true,
//     createdAt: faker.date.recent(),
//   },
//   {
//     id: faker.string.uuid(),
//     name: 'Sooth Ease',
//     price: Number(faker.commerce.price({ min: 1000, max: 5000 })),
//     stock: Math.floor(Math.random() * 100),
//     qty: 0,
//     image: DarkGreenChair,
//     subPhotos: [],
//     category: ProductCategory.CHAIR,
//     isFeatured: true,
//     createdAt: faker.date.recent(),
//   },
//   {
//     id: faker.string.uuid(),
//     name: 'Cozy Retreat',
//     price: Number(faker.commerce.price({ min: 1000, max: 5000 })),
//     stock: Math.floor(Math.random() * 100),
//     qty: 0,
//     image: GrayChair,
//     subPhotos: [],
//     category: ProductCategory.CHAIR,
//     isFeatured: false,
//     createdAt: faker.date.recent(),
//   },
//   {
//     id: faker.string.uuid(),
//     name: 'Chic Sway',
//     price: Number(faker.commerce.price({ min: 1000, max: 5000 })),
//     stock: Math.floor(Math.random() * 100),
//     qty: 0,
//     image: OfficeChair,
//     subPhotos: [],
//     category: ProductCategory.CHAIR,
//     isFeatured: false,
//     createdAt: faker.date.recent(),
//   },
//   {
//     id: faker.string.uuid(),
//     name: 'Wooden Trip',
//     price: Number(faker.commerce.price({ min: 1000, max: 5000 })),
//     stock: Math.floor(Math.random() * 100),
//     qty: 0,
//     image: WoodenChair,
//     subPhotos: [],
//     category: ProductCategory.CHAIR,
//     isFeatured: false,
//     createdAt: faker.date.recent(),
//   },
//   {
//     id: faker.string.uuid(),
//     name: 'Cloud Comfort',
//     price: Number(faker.commerce.price({ min: 1000, max: 5000 })),
//     stock: Math.floor(Math.random() * 100),
//     qty: 0,
//     image: WhiteChair2,
//     subPhotos: [],
//     category: ProductCategory.CHAIR,
//     isFeatured: false,
//     createdAt: faker.date.recent(),
//   },
//   {
//     id: faker.string.uuid(),
//     name: 'Radiant Relax',
//     price: Number(faker.commerce.price({ min: 1000, max: 5000 })),
//     stock: Math.floor(Math.random() * 100),
//     qty: 0,
//     image: WhiteChair,
//     subPhotos: [],
//     category: ProductCategory.CHAIR,
//     isFeatured: false,
//     createdAt: faker.date.recent(),
//   },
// ] satisfies Product[];
